// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAl4YNhX8TaM7IFV_8wfAlnMjWj54Qgx0A',
    appId: '1:944524172058:web:f2824260b3883395692aa3',
    messagingSenderId: '944524172058',
    projectId: 'paykr-v1',
    authDomain: 'paykr-v1.firebaseapp.com',
    storageBucket: 'paykr-v1.appspot.com',
    measurementId: 'G-YY3DCX6JGQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyASiwEaAde47gKWbS6WeNlga0EvkUWX0e8',
    appId: '1:944524172058:android:30d445f265662326692aa3',
    messagingSenderId: '944524172058',
    projectId: 'paykr-v1',
    storageBucket: 'paykr-v1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCz58BA3-etUm0CrnDzUSpsZezb6sw1H6E',
    appId: '1:944524172058:ios:9607d7fa9743ef23692aa3',
    messagingSenderId: '944524172058',
    projectId: 'paykr-v1',
    storageBucket: 'paykr-v1.appspot.com',
    iosBundleId: 'com.HexaCreators.paykr.paykr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCz58BA3-etUm0CrnDzUSpsZezb6sw1H6E',
    appId: '1:944524172058:ios:9607d7fa9743ef23692aa3',
    messagingSenderId: '944524172058',
    projectId: 'paykr-v1',
    storageBucket: 'paykr-v1.appspot.com',
    iosBundleId: 'com.HexaCreators.paykr.paykr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAl4YNhX8TaM7IFV_8wfAlnMjWj54Qgx0A',
    appId: '1:944524172058:web:dd9f574aa7c0ed45692aa3',
    messagingSenderId: '944524172058',
    projectId: 'paykr-v1',
    authDomain: 'paykr-v1.firebaseapp.com',
    storageBucket: 'paykr-v1.appspot.com',
    measurementId: 'G-QB8EM0LBRN',
  );

}